stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ''

services:
  - docker:dind

build:
  stage: build
  image: docker:latest
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 27.71.25.178 >> ~/.ssh/known_hosts
  script:
    - ssh root@27.71.25.178 "cd g2b-admin && git pull"
    - ssh root@27.71.25.178 "cd g2b-admin && docker-compose build"

deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 27.71.25.178 >> ~/.ssh/known_hosts
  script:
    - ssh root@27.71.25.178 "cd g2b-admin && docker-compose down"
    - ssh root@27.71.25.178 "cd g2b-admin && docker-compose up -d"
