stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ''

services:
  - docker:dind

before_script:
  - apk add --no-cache openssh
  - mkdir -p ~/.ssh
  # Add the private key
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  # Add the server to known hosts
  - ssh-keyscan -H 27.71.25.178 >> ~/.ssh/known_hosts

build:
  stage: build
  image: docker:latest
  script:
    - ssh root@27.71.25.178 "cd g2b-admin && git pull"
    - ssh root@27.71.25.178 "cd g2b-admin && docker-compose build"

deploy:
  stage: deploy
  image: docker:latest
  script:
    - ssh root@27.71.25.178 "cd g2b-admin && docker-compose down"
    - ssh root@27.71.25.178 "cd g2b-admin && docker-compose up -d"
