stages:
  - build
  - deploy

build:
  stage: build
  image: alpine
  before_script:
    - apk add --no-cache openssh-client
    - echo "$REMOTE_PASSWORD" | sshpass ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "echo 'Connection successful'"
  script:
    - echo "$REMOTE_PASSWORD" | sshpass ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "cd g2b-admin && git pull"
    - echo "$REMOTE_PASSWORD" | sshpass ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "cd g2b-admin && docker-compose build"

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache openssh-client sshpass
  script:
    - echo "$REMOTE_PASSWORD" | sshpass ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "cd g2b-admin && docker-compose down"
    - echo "$REMOTE_PASSWORD" | sshpass ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "cd g2b-admin && docker-compose up -d"
