stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ''

services:
  - docker:dind

build:
  stage: build
  image: docker:latest
  script:
    - docker-compose build

deploy:
  stage: deploy
  image: docker:latest
  script:
    - docker-compose down
    - docker-compose up -d
